core/backend_lama/controllers/TimbanganIncomingController.php
<?php

namespace backend\controllers;

use common\models\DataPo;
use common\models\StagingStock;
use Yii;
use common\models\TimbanganIncoming;
use common\models\TimbanganIncomingSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TimbanganIncomingController implements the CRUD actions for TimbanganIncoming model.
 */
class TimbanganIncomingController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TimbanganIncoming models.
     * @return mixed
     */
     
     public function actionBackgroundJob(){
         $data=\common\models\TimbanganIncoming::find()->orderBy('id DESC')->one();
         $no=25;
         for ($no=1; $no < 25; $no++ ){
             $model= new \common\models\TimbanganIncoming();
             $model->no_spj=$data->no_spj;
              $model->no_pol=$data->no_pol;
               $model->id_po=$data->id_po;
                $model->tanggal_masuk=$data->tanggal_masuk;
                 $model->tanggal_keluar=$data->tanggal_keluar;
                  $model->jam_masuk=$data->jam_masuk;
                   $model->jam_keluar=$data->jam_keluar;
                    $model->nilai_masuk=$data->nilai_masuk;
                     $model->nilai_keluar=$data->nilai_keluar;
                      $model->subtotal=$data->subtotal;
                       $model->qty_po=$data->qty_po;
                        $model->create_by=$data->create_by;
                         $model->update_by=$data->update_by;
                          $model->delete_mark=$data->delete_mark;
                           $model->line_order=$data->line_order;
                           $model->save(false);
         }
     }
     
    public function actionIndexIn()
    {
        $searchModel = new TimbanganIncomingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index-in', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCetakSpj($id){
        $datatimbangan=TimbanganIncoming::find()->where(['id'=>$id])->one();
        $datapo=DataPo::find()->where(['id'=>$datatimbangan->id_po])->one();
        return $this->renderAjax('cetak-spj', [
          'datatimbangan'=>$datatimbangan,
          'datapo'=>$datapo,
        ]);
    }
    public function actionIndex()
    {
        $searchModel = new TimbanganIncomingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionIn()
    {
        $searchModel = new TimbanganIncomingSearch();
        $dataProvider = $searchModel->searchin(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TimbanganIncoming model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionPilihData($id, $idbill)
    {
        $model = new DataPo();
        if ($model->load(Yii::$app->request->post())) {
            $cekdata=DataPo::find()->where(['id'=>$id])->one();
            $cekdata->sisa_qty=$cekdata->sisa_qty-$model->sisa_qty;
            $dataincoming = TimbanganIncoming::find()->where(['id' => $idbill])->one();
            $dataincoming->id_po = $id;
            $dataincoming->qty_po=$model->sisa_qty;
            $cekdata->save(false);
            $dataincoming->save(false);
            return $this->redirect(['view-in', 'id' => $idbill]);
        }


        return $this->renderAjax('tambah-quantity', [
            'model' => $model,
        ]);
    }
    public function actionCancelData($id, $idbill)
    {
        $dataincoming = TimbanganIncoming::find()->where(['id' => $idbill])->one();
        $datapo=DataPo::find()->where(['id'=>$id])->one();
        $datapo->sisa_qty=$datapo->sisa_qty+$dataincoming->qty_po;
        $dataincoming->id_po = 0;
        $dataincoming->qty_po=0;
        $datapo->save(false);
        $dataincoming->save(false);
        return $this->redirect(['view-in', 'id' => $idbill]);
    }
    public function actionViewIn($id)
    {
        $modelpo = new DataPo();
        $model = $this->findModel($id);
        if ($modelpo->load(Yii::$app->request->post())) {
            $modelpo->no_po1 = strtoupper($modelpo->no_po1);
            if ($modelpo->no_po1) {
                $datapo = DataPo::find()->where(['status' => 'Open'])->where(['no_po' => $modelpo->no_po1])->andWhere(['delete_mark' => 0])->all();
            } else {
                $datapo = DataPo::find()->where(['status' => 'Open'])->andWhere(['delete_mark' => 0])->all();
            }
            return $this->render('view-in', [
                'modelpo' => $modelpo,
                'model' => $model,
                'datapo' => $datapo,
            ]);
        }
        if ($model->load(Yii::$app->request->post())) {
            if ($model->nilai_keluar > 0) {
                if($model->nilai_keluar >= $model->nilai_masuk){
                    \Yii::$app->getSession()->setFlash('error', 'Nilai Timbangan Keluar Tidak Boleh Melebihin Nilai Timbangan Masuk');
                    return $this->redirect(['view-in', 'id' => $model->id]);
                }

                $datapo = DataPo::find()->where(['id' => $model->id_po])->one();
                $datastaging = StagingStock::find()->where(['id_plant' => $datapo->id_plant])->andWhere(['id_mat' => $datapo->material])->orderBy('id DESC')->one();
                if ($datastaging) {
                    $datastaging->qty = $datastaging->qty + ($model->nilai_masuk - $model->nilai_keluar);
                    $datastaging->last_update = date("Y-m-d h:i:sa");
                } else {
                    $datastaging = new StagingStock();
                    $datastaging->id_plant = $datapo->id_plant;
                    $datastaging->id_mat = $datapo->material;
                    $datastaging->qty = $model->nilai_masuk - $model->nilai_keluar;
                    $datastaging->last_update = date("Y-m-d h:i:sa");
                }
                if($datapo->sisa_qty=0){
                    $datapo->status = 'Close';
                }else{
                    $datapo->status = 'Open';
                }
               
                $model->subtotal = $model->nilai_masuk - $model->nilai_keluar;
                $datastaging->save(false);
                $datapo->save(false);
                $model->save(false);
                \Yii::$app->getSession()->setFlash('success', 'Timbangan Keluar Berhasil Diinput');
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                if ($model->nilai_masuk < 1) {
                    \Yii::$app->getSession()->setFlash('error', 'Nilai Timbangan Tidak Boleh 0');
                    return $this->redirect(['view-in', 'id' => $model->id]);
                }
                $datapo = DataPo::find()->where(['id' => $model->id_po])->one();
                $datapo->status = 'Timbangan Masuk';
                $datapo->save(false);
                $model->save(false);
                \Yii::$app->getSession()->setFlash('success', 'Timbangan Masuk Berhasil Diinput');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        if ($model->id_po > 0) {
            $datapo = DataPo::find()->where(['status' => 'Open'])->orWhere(['status'=>'Timbangan Masuk'])->andWhere(['id' => $model->id_po])->andWhere(['delete_mark' => 0])->all();
        } else {
            $datapo = DataPo::find()->where(['status' => 'Open'])->orWhere(['status'=>'Timbangan Masuk'])->andWhere(['>','sisa_qty',0])->andWhere(['delete_mark' => 0])->all();
        }


        return $this->render('view-in', [
            'modelpo' => $modelpo,
            'model' => $model,
            'datapo' => $datapo,
        ]);
    }

    /**
     * Creates a new TimbanganIncoming model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TimbanganIncoming();
        $model->delete_mark = 0;

        $model->create_by = \yii::$app->user->identity->username;
        //  $model->jam_keluar=date("H:i:s");

        if ($model->load(Yii::$app->request->post())) {
            $model->no_pol = strtoupper($model->no_pol);
            // print_r($model->no_pol);die();
            $cekdata = TimbanganIncoming::find()->where(['id_po' => $model->id_po])->orderBy('id DESC')->one();
            $cekdatanopol = TimbanganIncoming::find()->where(['no_pol' => $model->no_pol])->orderBy('id DESC')->one();

            if ($cekdatanopol && $cekdatanopol->nilai_keluar < 1) {

                //  $cekdata->nilai_keluar = $model->nilai_masuk;
                //  $cekdata->subtotal = $cekdata->nilai_masuk - $cekdata->nilai_keluar;
                $cekdatanopol->update_by = \yii::$app->user->identity->username;
                $cekdatanopol->jam_keluar = date("H:i:s");
                $cekdatanopol->tanggal_keluar = date('Y-m-d');
                // $datapo = DataPo::find()->where(['id' => $model->id_po])->orderBy('id DESC')->one();
                // $datapo->status = 'Close';
                // $datapo->save(false);

core/backend_lama/views/timbangan-incoming/_form.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\DetailView;
/* @var $this yii\web\View */
/* @var $model common\models\TimbanganIncoming */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="box">
    <div class="box-body">
        <div class="timbangan-incoming-form">

            <?php $form = ActiveForm::begin(); ?>
            <div class="col-md-10">
                <?= $form->field($model, 'no_pol')->textInput(['placeholder' => 'No Pol','style' => 'text-transform:uppercase'])->label(false) ?>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <?= Html::submitButton('Search', ['class' => 'btn btn-default']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>
<div class="box">
    <div class="box-body">
        <div class="timbangan-incoming-view">




            <div class="col-md-6">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        //  'id',
                        'no_spj',

                        'id_po',
                        'tanggal_masuk',
                        'tanggal_keluar',
                        'jam_masuk',


                    ],
                ]) ?>
            </div>
            <div class="col-md-6">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        //  'id',

                        'jam_keluar',

                        'nilai_masuk',

                        'nilai_keluar',

                        'subtotal',

                    ],
                ]) ?>
            </div>

        </div>
        <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'nilai_masuk')->textInput(['type' => 'number','placeholder'=>'Nilai Timbangan','style'=>'text-align:center; height: 70px ','readOnly'=>true])->label(false) ?>
        <?php ActiveForm::end(); ?>
    </div>
</div>

core/backend_lama/views/timbangan-incoming/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\TimbanganIncomingSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="timbangan-incoming-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'no_spj') ?>

    <?= $form->field($model, 'id_po') ?>

    <?= $form->field($model, 'tanggal_masuk') ?>

    <?= $form->field($model, 'tanggal_keluar') ?>

    <?php // echo $form->field($model, 'jam_masuk') ?>

    <?php // echo $form->field($model, 'jam_keluar') ?>

    <?php // echo $form->field($model, 'nilai_masuk') ?>

    <?php // echo $form->field($model, 'nilai_keluar') ?>

    <?php // echo $form->field($model, 'subtotal') ?>

    <?php // echo $form->field($model, 'create_by') ?>

    <?php // echo $form->field($model, 'update_by') ?>

    <?php // echo $form->field($model, 'delete_mark') ?>

    <?php // echo $form->field($model, 'line_order') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

core/backend_lama/views/timbangan-incoming/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model common\models\TimbanganIncoming */

$this->title = 'Timbangan Incoming';
$this->params['breadcrumbs'][] = ['label' => 'Timbangan Incomings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="timbangan-incoming-create">
    <ul class="nav nav-tabs pull-right">
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/timbangan-incoming/create']) ?>"> Create Timbangan</a>
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/timbangan-incoming/in']) ?>"> Timbangan Masuk</a>
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/timbangan-incoming/']) ?>"> Timbangan Close</a>


    </ul>
    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

core/backend_lama/views/timbangan-incoming/index-in.php
<?php

use common\models\ChildSholdto;
use common\models\DataPo;
use common\models\DataTruck;
use common\models\PtMasterDistrikSki;
use common\models\RfcZZappSelectSysplanSki;
use common\models\RfcZZcsdListMatSalesSki;
use common\models\RfcZZcsdShiptoSki;
use yii\helpers\Html;
use yii\grid\GridView;
use kartik\export\ExportMenu;
use common\models\MasterTax;
use common\models\Supir;
use common\models\TableExpeditur;
use common\models\TypeTruck;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\HargaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Timbangan Incomming';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <div class="pt-master-distrik-ski-index">

            <h3><?= Html::encode($this->title) ?></h3>
            <ul class="nav nav-tabs pull-right">
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/staging-stock']) ?>"> Staging Stock</a>
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/timbangan-incoming/index-in']) ?>">Timbangan Incomming</a>
               


            </ul>


            <?php // echo $this->render('_search', ['model' => $searchModel]); 
            ?>
            <?php
            $gridColumns = [
                ['class' => 'yii\grid\SerialColumn', 'header' => 'No'],
                //  'id',
                // 'id',
                'no_spj',
                [
                    'attribute' => 'id_po',
                    //'label' => 'Expeditur',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        $dataexpeditur = DataPo::find()->where(['id' => $model->id_po])->one();
                        // $datasupir=Supir::find()->where(['id'=>$datatruck->id_supir])->one();
                        if($dataexpeditur){
                            $status=$dataexpeditur->no_po;
                        }else{
                            $status='-'.$model->id_po;
                        }
                        return $status;
                    }
                ],
                [
                  //  'attribute' => 'nilai_keluar',
                    'label' => 'Plant',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        $dataexpeditur = DataPo::find()->where(['id' => $model->id_po])->one();
                       
                         if($dataexpeditur){
                              $plant=\common\models\RfcZZappSelectSysplanSki::find()->where(['id'=>$dataexpeditur->id_plant])->one();
                            $status=$plant->WERKS.' '.$plant->NAME1;
                        }else{
                            $status='Data Plant Tidak Ditemukan';
                        }
                        return $status;
                       
                    }
                ],
                [
                    //'attribute' => 'nilai_keluar',
                    'label' => 'Material',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        $dataexpeditur = DataPo::find()->where(['id' => $model->id_po])->one();
                         if($dataexpeditur){
                              $material=\common\models\RfcZZcsdListMatSalesSki::find()->where(['ID'=>$dataexpeditur->material])->one();
                            $status=$material->KODE_MATERIAL.' '.$material->DESKRIPSI;
                        }else{
                            $status='Data Mat Tidak Ditemukan';
                        }
                        return $status;
                       
                        
                    }
                ],
               // 'id_po',
                'tanggal_masuk',
                'tanggal_keluar',
                'jam_masuk',
                'jam_keluar',

                // [
                //     'attribute' => 'nilai_masuk',
                //     //'label' => 'Nilai Timbangan Masuk',
                //     'contentOptions' => ['class' => 'text-left'],
                //     'value' => function ($model) {
                //         //  $datatruck = Conveyor::find()->where(['id' => $model->id_conveyor])->one();
                //         return  number_format($model->nilai_masuk) . ' KG'; 
                //     }
                // ],
                // [
                //     'attribute' => 'nilai_keluar',
                //     //'label' => 'Nilai Timbangan Keluar',
                //     'contentOptions' => ['class' => 'text-left'],
                //     'value' => function ($model) {
                //         //  $datatruck = Conveyor::find()->where(['id' => $model->id_conveyor])->one();
                //         return number_format($model->nilai_keluar) . ' KG';
                //     }
                // ],
                [
                    'attribute' => 'subtotal',
                    //'label' => 'Berat Akhir',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        //  $datatruck = Conveyor::find()->where(['id' => $model->id_conveyor])->one();
                        return  number_format($model->subtotal,2) . ' KG';
                    }
                ],

              

               
            ];

            echo ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $gridColumns,
                'clearBuffers' => true, //optional
            ]);

            echo \kartik\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => $gridColumns
            ]);
            ?>


        </div>
    </div>
</div>

core/backend_lama/views/timbangan-incoming/index.php
<?php

use common\models\ChildSholdto;
use common\models\DataPo;
use common\models\DataTruck;
use common\models\PtMasterDistrikSki;
use common\models\RfcZZappSelectSysplanSki;
use common\models\RfcZZcsdListMatSalesSki;
use common\models\RfcZZcsdShiptoSki;
use yii\helpers\Html;
use yii\grid\GridView;
use kartik\export\ExportMenu;
use common\models\MasterTax;
use common\models\Supir;
use common\models\TableExpeditur;
use common\models\TypeTruck;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\HargaSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Timbangan Incomming';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <div class="pt-master-distrik-ski-index">

            <h3><?= Html::encode($this->title) ?></h3>
            <ul class="nav nav-tabs pull-right">
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/timbangan-incoming/create']) ?>"> Create Timbangan</a>
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/timbangan-incoming/in']) ?>"> Timbangan Masuk</a>
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/timbangan-incoming/']) ?>"> Timbangan Close</a>


            </ul>


            <?php // echo $this->render('_search', ['model' => $searchModel]); 
            ?>
            <?php
            $gridColumns = [
                ['class' => 'yii\grid\SerialColumn', 'header' => 'No'],
                //  'id',
                // 'id',
                'no_spj',
                [
                    'attribute' => 'id_po',
                    //'label' => 'Expeditur',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        $dataexpeditur = DataPo::find()->where(['id' => $model->id_po])->one();
                        // $datasupir=Supir::find()->where(['id'=>$datatruck->id_supir])->one();
                        return $dataexpeditur->no_po;
                    }
                ],
               // 'id_po',
                'tanggal_masuk',
                'tanggal_keluar',
                'jam_masuk',
                'jam_keluar',

                [
                    'attribute' => 'nilai_masuk',
                    //'label' => 'Nilai Timbangan Masuk',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        //  $datatruck = Conveyor::find()->where(['id' => $model->id_conveyor])->one();
                        return  number_format($model->nilai_masuk,2) . ' KG'; 
                    }
                ],
                [
                    'attribute' => 'nilai_keluar',
                    //'label' => 'Nilai Timbangan Keluar',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        //  $datatruck = Conveyor::find()->where(['id' => $model->id_conveyor])->one();
                        return number_format($model->nilai_keluar,2) . ' KG';
                    }
                ],
                [
                    'attribute' => 'subtotal',
                    //'label' => 'Berat Akhir',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        //  $datatruck = Conveyor::find()->where(['id' => $model->id_conveyor])->one();
                        return  number_format($model->subtotal,2) . ' KG';
                    }
                ],

              

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => ' {myButton}',  // the default buttons + your custom button
                    'buttons' => [
                        'myButton' => function ($url, $model, $key) {     // render your custom button
                            return Html::a('View', ['view', 'id' => $model->id]);
                        }
                    ]
                ]
            ];

            echo ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $gridColumns,
                'clearBuffers' => true, //optional
            ]);

            echo \kartik\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => $gridColumns
            ]);
            ?>


        </div>
    </div>
</div>

core/backend_lama/views/timbangan-incoming/tambah-quantity.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use kartik\money\MaskMoney;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
?>
<?php
$form = ActiveForm::begin();
?>

<div class="modal-header" style="background-color:#7fc6b6 ">
    <button type="button" class="close" data-dismiss="modal">&times;</button>


</div>
<div class="modal-body">
 
        <?= $form->field($model, 'sisa_qty')->textInput(['type'=>'number'])->label('Input QTY') ?>

   





</div>
<div class="modal-footer" style="background-color:#7fc6b6 ">
    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
<?php ActiveForm::end(); ?>

core/backend_lama/views/timbangan-incoming/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TimbanganIncoming */

$this->title = 'Update Timbangan Incoming: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Timbangan Incomings', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="timbangan-incoming-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

core/backend_lama/views/timbangan-incoming/view.php
<?php

use common\models\DataPo;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\TimbanganIncoming */

$this->title = $model->no_spj;
$this->params['breadcrumbs'][] = ['label' => 'Timbangan Incomings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="box">
    <div class="box-body">
        <div class="timbangan-incoming-view">

            <h1><?= Html::encode($this->title) ?></h1>


            <div class="col-md-6">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        //  'id',
                        'no_spj',
                        'no_pol',
                        [
                            'attribute' => 'id_po',
                            'label' => 'No PO',
                            'contentOptions' => ['class' => 'text-left'],
                            'value' => function ($model) {
                                $datatruck = DataPo::find()->where(['id' => $model->id_po])->one();
                                return $datatruck->no_po;
                            }
                        ],
                        //  'id_po',
                        'tanggal_masuk',
                        'tanggal_keluar',
                        'jam_masuk',


                    ],
                ]) ?>
            </div>
            <div class="col-md-6">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        //  'id',
                     //   'tanggal',
                        [
                            'attribute' => 'qty_po',
                            // 'label' => 'No PO',
                            'contentOptions' => ['class' => 'text-left'],
                            'value' => function ($model) {

                                return  number_format($model->qty_po) . ' TO';
                            }
                        ],
                        'jam_keluar',
                        [
                            'attribute' => 'nilai_masuk',
                            // 'label' => 'No PO',
                            'contentOptions' => ['class' => 'text-left'],
                            'value' => function ($model) {

                                return  number_format($model->nilai_masuk,2) . ' KG';
                            }
                        ],
                        // 'nilai_masuk',
                        [
                            'attribute' => 'nilai_keluar',
                            // 'label' => 'No PO',
                            'contentOptions' => ['class' => 'text-left'],
                            'value' => function ($model) {

                                return  number_format($model->nilai_keluar,2) . ' KG';
                            }
                        ],
                       //  'nilai_keluar',
                        [
                            'attribute' => 'subtotal',
                            // 'label' => 'No PO',
                            'contentOptions' => ['class' => 'text-left'],
                            'value' => function ($model) {

                                return number_format($model->subtotal,2) . ' KG';
                            }
                        ],
                        //  'subtotal',

                    ],
                ]) ?>
            </div>

        </div>
        <div class="col-md-12">
            <?= Html::a('Selesai', ['create'], ['class' => 'btn btn-default']) ?>
            <?= Html::a('Cetak SPJ', ['cetak-spj','id'=>$model->id],['class' => 'btn btn-success', 'target' => '_blank']) ?>
        </div>
    </div>
</div>