core/common/models/OPpSki.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "o_pp_ski".
 *
 * @property int $ID
 * @property string $order_type
 * @property string $order_number
 * @property int $line_number
 * @property string $create_by
 * @property string $create_date
 * @property string $update_by
 * @property string $update_date
 * @property int $delete_mark
 */
class OPpSki extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'o_pp_ski';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['order_type', 'order_number', 'line_number', 'create_by', 'create_date', 'update_by', 'update_date'], 'required'],
            [['line_number', 'delete_mark','status_op','id_soldto','status_timbangan_keluar'], 'integer'],
            [['create_date', 'update_date','time_create','time_update'], 'safe'],
            [['order_type', 'create_by', 'update_by','nama_soldto','alasan_cancel'], 'string', 'max' => 255],
            [['order_number'], 'string', 'max' => 10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'order_type' => 'SO Type',
            'order_number' => 'SO Number',
            'line_number' => 'Line Number',
            'create_by' => 'Create By',
            'create_date' => 'Create Date',
            'update_by' => 'Update By',
            'update_date' => 'Update Date',
            'delete_mark' => 'Delete Mark',
        ];
    }
}

core/backend/controllers/OPpSkiController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\OPpSki;
use common\models\OPpSkiSearch;
use common\models\ChildOPpSki;
use common\models\ChildSholdto;
use common\models\Harga;
use common\models\MasterTax;
use common\models\RfcZZappSelectSysplanSki;
use common\models\RfcZZcsdListMatSalesSki;
use common\models\RfcZZcsdShiptoSki;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OPpSkiController implements the CRUD actions for OPpSki model.
 */
class OPpSkiController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OPpSki models.
     * @return mixed
     */
    public function actionApproval($id, $ids, $status = null)
    {
        $datachild = ChildOPpSki::find()->where(['ID' => $id])->one();
        $datachild->approval_by = \yii::$app->user->identity->username;
        $datachild->approval_date = date('Y-m-d');
        $datachild->status_konfirmasi = 'Approval';
        $datachild->save(false);
        \Yii::$app->getSession()->setFlash('success', 'Data Berhasil DiApproval');
        return $this->redirect(['view', 'id' => $ids, 'status' => $status]);
    }
    public function actionReject($id, $ids, $status = null)
    {
        $datachild = ChildOPpSki::find()->where(['ID' => $id])->one();
        $datachild->approval_reject = \yii::$app->user->identity->username;
        $datachild->approval_date_reject = date('Y-m-d');
        $datachild->status_konfirmasi = 'Reject';
        $datachild->save(false);
        \Yii::$app->getSession()->setFlash('success', 'Data Berhasil Direject');
        return $this->redirect(['view', 'id' => $ids, 'status' => $status]);
    }
    public function actionDeleteChild($id, $ids)
    {
        $datachild = ChildOPpSki::find()->where(['ID' => $id])->one();

        $datachild->delete_mark = 1;
        $datachild->status_konfirmasi = 'Delete';
        $datachild->save(false);
        \Yii::$app->getSession()->setFlash('success', 'Data Berhasil Didelete');
        return $this->redirect(['view', 'id' => $ids]);
    }

    public function actionCancelDataTransaksi($id){
        $model=OPpSki::find()->where(['ID'=>$id])->one();
        if ($model->load(Yii::$app->request->post())) {
            $model->delete_mark=1;
            $model->update_by=\yii::$app->user->identity->username;
            $model->update_date=date('Y-m-d');
            $model->time_update=date('H:i:s');
            $model->save(false);
            \Yii::$app->getSession()->setFlash('success', 'Data Berhasil Dicancel');
            return $this->redirect(['cancel-transaksi']);
        }
        return $this->renderAjax('cancel-data', [
           'model'=>$model,
        ]);
    }
    public function actionIndex()
    {
        $searchModel = new OPpSkiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionCancelTransaksi()
    {
        $searchModel = new OPpSkiSearch();
        $dataProvider = $searchModel->searchcancel(Yii::$app->request->queryParams);

        return $this->render('index-cancel', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    public function actionDataPp()
    {
        $searchModel = new OPpSkiSearch();
        $dataProvider = $searchModel->searchpp(Yii::$app->request->queryParams);

        return $this->render('index-pp', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OPpSki model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id, $status = null)
    {
        $datachild = ChildOPpSki::find()->where(['id_pp' => $id])->andWhere(['delete_mark' => 0])->all();
        return $this->render('view', [
            'status' => $status,
            'datachild' => $datachild,
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new OPpSki model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionListregss($id = null)
    {
       
        if ($id) {
            $hitungdata = \common\models\Harga::find()
                ->where(['SOLD_TO' => $id])


                ->count();
               
            $regs = \common\models\Harga::find()
                ->where(['SOLD_TO' => $id])

                
                ->all();

               
            if ($hitungdata > 0) {
                // $idsatuan=[];
                $idchild=[];
                echo
                "<option value=" . 'Pilih . . .' . "'>" . 'Pilih . . .' . "</option>  <br/>";
                foreach ($regs as $reg) {
                    $idchild[]=$reg->SHIP_TO;
                }
                $datachild = ChildSholdto::find()->where(['ID' => $idchild])->all();
              //  print_r($datachild);die();
                    if ($datachild) {
                        foreach($datachild as $keyc =>$valchil){
                            echo


                            "<option value='" . $valchil->ID . "'>" . $valchil->NAMA_SHIPTO . "</option>";
                  
                        }
                            } else {
                        
                        echo  "<option value=" . '' . "'>" . 'Shipto Belum Terdaftar Ditable Harga' . "</option>  <br/>";
                    }
            }
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionListregplant($id = null)
    {
        if ($id) {
             $tanggalsekarang=date('Y-m-d');
             $tanggalkecil=date('Y-m-d', strtotime('-1 days', strtotime($tanggalsekarang)));
             $tanggalbesar=date('Y-m-d', strtotime('+1 days', strtotime($tanggalsekarang)));
            $hitungdata = \common\models\Harga::find()
                ->where(['SHIP_TO' => $id])
                ->andWhere(['<','VALID_FROM',$tanggalkecil])->andWhere(['>','VALID_TO',$tanggalbesar])

                ->count();

            $regs = \common\models\Harga::find()
                ->where(['SHIP_TO' => $id])
                ->andWhere(['<','VALID_FROM',$tanggalkecil])->andWhere(['>','VALID_TO',$tanggalbesar])
                ->orderBy([
                    'ID' => SORT_ASC,
                ])
                ->all();


            if ($hitungdata > 0) {
                // $idsatuan=[];

                echo
                "<option value=" . 'Pilih . . .' . "'>" . 'Pilih . . .' . "</option>  <br/>"; 
                foreach ($regs as $reg) {
                   
                    $datachild = RfcZZcsdListMatSalesSki::find()->where(['ID' => $reg->KODE])->one();
                    if ($datachild) {
                        echo


                        "<option value='" . $datachild->ID . "'>" . $datachild->KODE_MATERIAL . '-' . $datachild->DESKRIPSI . "</option>";
                    } else {
                        echo  "<option value=" . '' . "'>" . 'Material Belum Terdaftar Ditable Harga' . "</option>  <br/>";
                    }
                }
            }
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionGetharga($id = null)
    {
        if ($id) {
            $hitungdata = \common\models\Harga::find()
                ->where(['KODE' => $id])


                ->count();

            $regs = \common\models\Harga::find()
                ->where(['KODE' => $id])

                ->orderBy([
                    'ID' => SORT_ASC,
                ])
                ->all();


            if ($hitungdata > 0) {
                // $idsatuan=[];


                foreach ($regs as $reg) {
                    // $datachild = RfcZZcsdListMatSalesSki::find()->where(['ID' => $reg->KODE])->one();

                    echo


                    "<option value='" . $reg->HARGA . "'>" . 'Rp.' . $reg->HARGA . "</option>";
                }
            }
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionListregsoldto($id = null)
    {
        if ($id) {
            $hitungdata = \common\models\Harga::find()
                ->where(['PLANT' => $id])


                ->count();

            $regs = \common\models\Harga::find()
                ->where(['PLANT' => $id])

                ->orderBy([
                    'ID' => SORT_ASC,
                ])
                ->all();


            if ($hitungdata > 0) {
                // $idsatuan=[];
                $idplant=[];
                echo
                "<option value=" . 'Pilih . . .' . "'>" . 'Pilih . . .' . "</option>  <br/>";
                foreach ($regs as $reg) {
                   $idplant[]=$reg->SOLD_TO;
                }
                $datachild = RfcZZcsdShiptoSki::find()->where(['ID' => $idplant])->all();
                if ($datachild) {
                    foreach ($datachild as $keys =>$vals){
                        echo


                        "<option value='" . $vals->ID . "'>" . $vals->KODE_SOLDTO . '-' . $vals->NAMA_SOLDTO . "</option>";
               
                    }
                        } else {
                    echo  "<option value=" . '' . "'>" . 'Plant Belum Terdaftar Ditable Harga' . "</option>  <br/>";
                }
            }
        } else {

core/backend/views/o-pp-ski/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model common\models\OPpSki */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="box">
    <div class="box-body">
        <div class="opp-ski-form">
       
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'order_type')->widget(\kartik\select2\Select2::classname(), [
                    'data' => ArrayHelper::map(common\models\TypeMaster::find()->asArray()->all(), 'code_type', 'deskripsi'),
                    'language' => 'eng',
                    'options' => ['placeholder' => 'Pilih Type...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>

           

            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

core/backend/views/o-pp-ski/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\OPpSkiSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="opp-ski-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID') ?>

    <?= $form->field($model, 'order_type') ?>

    <?= $form->field($model, 'order_number') ?>

    <?= $form->field($model, 'line_number') ?>

    <?= $form->field($model, 'create_by') ?>

    <?php // echo $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'update_by') ?>

    <?php // echo $form->field($model, 'update_date') ?>

    <?php // echo $form->field($model, 'delete_mark') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

core/backend/views/o-pp-ski/cancel-data.php
<?php

use common\models\Harga;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use kartik\money\MaskMoney;
use kartik\date\DatePicker;
use yii\helpers\ArrayHelper;
?>
<?php
$form = ActiveForm::begin();
?>


<div class="modal-body">

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'alasan_cancel')->textInput() ?>
        </div>
        <div class="modal-footer">
            <div class="col-md-12" style="text-align: left;">
                <?= Html::submitButton('Ubah', ['class' => 'btn btn-primary']) ?>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>

core/backend/views/o-pp-ski/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model common\models\OPpSki */

$this->title = 'Create SO';
$this->params['breadcrumbs'][] = ['label' => 'O Pp Skis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="opp-ski-create">
    <ul class="nav nav-tabs pull-right">
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/data-pp']) ?>"> Data PP</a>
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/create']) ?>"> Create PP</a>
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/']) ?>"> Approval PP</a>


    </ul>
    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

core/backend/views/o-pp-ski/index-cancel.php
<?php

use common\models\PtMasterDistrikSki;
use yii\helpers\Html;
use yii\grid\GridView;
use kartik\export\ExportMenu;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel common\models\RfcZZcsdShiptoSkiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Cancel Data';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <div class="rfc-zzapp-select-sysplan-ski-index">

            <h3><?= Html::encode($this->title) ?></h3>
            

 
            <?php // echo $this->render('_search', ['model' => $searchModel]); 
            ?>
            <?php
            $gridColumns = [
                ['class' => 'yii\grid\SerialColumn', 'header' => 'No'],
                'order_type',
                'nama_soldto',
                'order_number',
                // 'line_number',
                'create_by',
                [
                    'attribute' => 'create_date',
                   
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                       
                        return $model->create_date .'|'.$model->time_create;
                    }
                ], 
                //'update_by',
                [
                    'attribute' => 'update_date',
                   
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                       
                        return $model->update_date .'|'.$model->time_update;
                    }
                ],
                //'delete_mark',

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => ' {myButton}',  // the default buttons + your custom button
                    'buttons' => [
                        'myButton' => function ($url, $model, $key) {     // render your custom button
                            return Html::a('Cancel Transaksi', ['cancel-data-transaksi', 'id' => $model->ID],['data-target'=>"#modalvote" ,'data-toggle'=>"modal"]);
                        }
                    ]
                ]
            ];

            echo ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $gridColumns,
                'clearBuffers' => true, //optional
            ]);

            echo \kartik\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => $gridColumns
            ]);
            ?>



        </div>
    </div>
</div>
<div class="modal remote fade" id="modalvote">
    <div class="modal-dialog">
        <div class="modal-content loader-lg"></div>
    </div>
</div>

core/backend/views/o-pp-ski/index-pp.php
<?php

use common\models\PtMasterDistrikSki;
use yii\helpers\Html;
use yii\grid\GridView;
use kartik\export\ExportMenu;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel common\models\RfcZZcsdShiptoSkiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Approval Data';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <div class="rfc-zzapp-select-sysplan-ski-index">

            <h3><?= Html::encode($this->title) ?></h3>
            <ul class="nav nav-tabs pull-right">
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/data-pp']) ?>"> Data SO</a>
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/create']) ?>"> Create SO</a>
                <?php if (\yii::$app->user->identity->role == 'admin' ||\yii::$app->user->identity->role == 'admin') { ?>
                    <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/']) ?>"> Approval SO</a>
                <?php } ?>
            </ul>


            <?php // echo $this->render('_search', ['model' => $searchModel]); 
            ?>
            <?php
            $gridColumns = [
                ['class' => 'yii\grid\SerialColumn', 'header' => 'No'],
                'order_type',
                'nama_soldto',
                'order_number',
                // 'line_number',
                'create_by',
                [
                    'attribute' => 'create_date',

                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {

                        return $model->create_date . '|' . $model->time_create;
                    }
                ],
                //'update_by',
                [
                    'attribute' => 'update_date',

                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {

                        return $model->update_date . '|' . $model->time_update;
                    }
                ],
                [
                    'attribute' => 'status_op',
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                        if ($model->status_op == 0) {
                            $keterangan = 'Proses Input Order';
                        }else if($model->delete_mark==1){
                            $keterangan = 'Data Dicancel';
                        }
                         else if ($model->status_op == 1) {
                            $keterangan = 'Open';
                        } else if ($model->status_op == 2) {
                            $keterangan = 'Approval';
                        } else {
                            $keterangan = 'Telah Diproses';
                        }
                        return $keterangan;
                    }
                ],
                'alasan_cancel',
                //  'status_op',
                //'update_by',
                //'update_date',
                //'delete_mark',

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => ' {myButton} {update}',  // the default buttons + your custom button
                    'buttons' => [

                        'myButton' => function ($url, $model, $key) {     // render your custom button

                            return Html::a('', ['view', 'id' => $model->ID,], ['class' => 'fa fa-eye', 'title' => 'Lihat Data']);
                        },
                      
                        'update' => function ($url, $model, $key) {
                            // render your custom button
                            if($model->delete_mark==0){
                                if ($model->status_op == 1 || $model->status_op == 0) {
                                    return Html::a('', ['update', 'id' => $model->ID,], ['class' => 'fa fa-pencil-square-o', 'title' => 'Ubah Data']);
                                }
                            }
                          
                        },
                       
                    ]
                ]
            ];

            echo ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $gridColumns,
                'clearBuffers' => true, //optional
            ]);

            echo \kartik\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => $gridColumns
            ]);
            ?>



        </div>
    </div>
</div>

core/backend/views/o-pp-ski/index.php
<?php

use common\models\PtMasterDistrikSki;
use yii\helpers\Html;
use yii\grid\GridView;
use kartik\export\ExportMenu;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel common\models\RfcZZcsdShiptoSkiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Approval Data';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <div class="rfc-zzapp-select-sysplan-ski-index">

            <h3><?= Html::encode($this->title) ?></h3>
            <ul class="nav nav-tabs pull-right">
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/data-pp']) ?>"> Data SO</a>
                <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/create']) ?>"> Create SO</a>
                <?php if (\yii::$app->user->identity->role == 'admin' ||\yii::$app->user->identity->role == 'admin') { ?>
                    <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/']) ?>"> Approval SO</a>
                <?php } ?>

            </ul>

 
            <?php // echo $this->render('_search', ['model' => $searchModel]); 
            ?>
            <?php
            $gridColumns = [
                ['class' => 'yii\grid\SerialColumn', 'header' => 'No'],
                'order_type',
                'nama_soldto',
                'order_number',
                // 'line_number',
                'create_by',
                [
                    'attribute' => 'create_date',
                   
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                       
                        return $model->create_date .'|'.$model->time_create;
                    }
                ],
                //'update_by',
                [
                    'attribute' => 'update_date',
                   
                    'contentOptions' => ['class' => 'text-left'],
                    'value' => function ($model) {
                       
                        return $model->update_date .'|'.$model->time_update;
                    }
                ],
                //'delete_mark',

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => ' {myButton}',  // the default buttons + your custom button
                    'buttons' => [
                        'myButton' => function ($url, $model, $key) {     // render your custom button
                            return Html::a('View', ['view', 'id' => $model->ID, 'status' => 'Approval']);
                        }
                    ]
                ]
            ];

            echo ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $gridColumns,
                'clearBuffers' => true, //optional
            ]);

            echo \kartik\grid\GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => $gridColumns
            ]);
            ?>



        </div>
    </div>
</div>

core/backend/views/o-pp-ski/update.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\OPpSki */

$this->title = 'Update O Pp Ski: ' . $model->ID;
$this->params['breadcrumbs'][] = ['label' => 'O Pp Skis', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ID, 'url' => ['view', 'id' => $model->ID]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="opp-ski-update">
<ul class="nav nav-tabs pull-right">
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/data-pp']) ?>"> Data PP</a>
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/create']) ?>"> Create PP</a>
        <a class="btn btn-warning btn-sm" href="<?= Url::toRoute(['/o-pp-ski/']) ?>"> Approval PP</a>


    </ul>
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>